name: Deploy Images to GHCR

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  rsnano_com_publish:
    name: Publish rsnano.com Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/rsnano-node/rsnano-com:latest
          docker push ghcr.io/rsnano-node/rsnano-com:latest

